language: php

php:
  - hhvm
  - nightly
  - 7
  - 5.6
  - 5.5

matrix:
  fast_finish: true

before_script:
  - if [ $TRAVIS_PHP_VERSION != "hhvm" ]; then phpenv config-rm xdebug.ini ; fi
  - composer self-update
  - composer install -n

script:
- composer test
